<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Helpdesk.Application\Helpdesk.Application.csproj" />
    <ProjectReference Include="..\..\..\..\src\Hansom.Postgresql\Hansom.Postgresql.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
